#!/bin/bash

sudo apt-get update -y
sudo apt-get upgrade -y
sudo apt install python3-pip -y
pip3 install locust
git clone https://github.com/giovanialtelino/Locust-Test.git
cd Locust-Test
locust -f second.py --master